version: "3"

services:
  fastapiback:
    build: .
    container_name: fpv-fastapi
    restart: always
    # DESCOMENTAR PARA PRUEBAS LOCALES
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    environment:
      - DB_URL=postgresql://postgres:password@postgres:5432/db-test
      # - DB_URL=postgresql://fpv_user_dev:pfv_user_pwd@postgres:5432/fpv_db_dev
      - SECRET_KEY="supreSecretKey123."
      # DEJAR EN FALSE PARA PRODUCCION
      - DEBUG=False
      # CAMBIAR POR LA IP DE LA MAQUINA DONDE SE EJECUTA REDIS
      - REDIS_URL=redis://redis:6379
    ports:
      - "8080:80"
      - "3500:8080"
      - "5432:5432"
    depends_on:
      - postgres
    volumes:
      - ./public:/app/public
    networks:
      - fpv-network

  # SOLO PRUEBAS
  # postgres:
  #   image: postgres:13.2
  #   restart: always
  #   environment:
  #     - POSTGRES_HOST=localhost
  #     - POSTGRES_DB=fpv_db_dev
  #     - POSTGRES_USER=fpv_user_dev
  #     - POSTGRES_PASSWORD=pfv_user_pwd
  #   ports:
  #     - '5080:5432'
  #   networks:
  #     - fpv-network
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - fpv-network
    volumes:
      - redis_data:/data

  workertres:
    build:
      context: .
      dockerfile: dockerfile-worker
    restart: always
    ports:
      - "5556:5555"
      - "5432:5432"
    environment:
      - DB_URL=postgresql://postgres:password@postgres:5432/db-test
      # CAMBIAR POR LA IP DE LA MAQUINA DONDE SE EJECUTA REDIS
      - REDIS_URL=redis://redis:6379
      #  DIRECTORIO DE ARCHIVOS ESTATICOS
      - PUBLIC_DIR=http://localhost:8080
    depends_on:
      - redis
    volumes:
      - ./public:/app/public
    networks:
      - fpv-network

networks:
  fpv-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
