version: "3"

services:
  fastapiback:
    build: .
    container_name: fpv-fastapi
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    environment:
      - DB_URL=postgresql://postgres:password@postgres:5432/db-test
      - SECRET_KEY="supreSecretKey123."
      # CAMBIAR POR LA IP DE LA MAQUINA DONDE SE EJECUTA
      - BASE_URL=http://localhost:8080
      # DEJAR EN FALSE PARA PRODUCCION
      - DEBUG=False
      # CAMBIAR POR LA IP DE LA MAQUINA DONDE SE EJECUTA REDIS
      - REDIS_URL=redis://redis:6379
    ports:
      - "3500:8080"
      - "4444:4444"
      - "5432:5432"
      - "6379:6379"
    volumes:
      - ./public:/app/public
    networks:
      - fpv-network

  nginx:
    image: nginx:latest
    container_name: fpv-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapiback
    networks:
      - fpv-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - fpv-network
    volumes:
      - redis_data:/data

  workertres:
    build:
      context: .
      dockerfile: dockerfile-worker
    restart: always
    ports:
      - "5556:5555"
      - "5432:5432"
    environment:
      - DB_URL=postgresql://postgres:password@postgres:5432/db-test
      #- CELERY_BROKER_URL=redis://redis:6379/0
      #- CELERY_RESULT_BACKEND=redis://redis:6379/0
      # CAMBIAR POR LA IP DE LA MAQUINA DONDE SE EJECUTA REDIS
      - REDIS_URL=redis://redis:6379
      #  DIRECTORIO DE ARCHIVOS ESTATICOS
      - PUBLIC_DIR=http://localhost:8080
    depends_on:
      - redis
    volumes:
      - ./public:/app/public
    networks:
      - fpv-network

networks:
  fpv-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
